[package]
name = "anki-api-server"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false
description = "Headless HTTP API server for Anki collections"

[[bin]]
path = "main.rs"
name = "anki-api-server"

[dependencies]
anki = { workspace = true, features = ["rustls"] }
anki_proto.workspace = true
axum.workspace = true
data-encoding.workspace = true
dirs.workspace = true
prost.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
toml.workspace = true
tokio.workspace = true
tower-http = { workspace = true, features = ["trace"] }
tracing.workspace = true
